export const API_CONSTANTS = {
  AUTH: {
    LOGIN: "api/auth/login",
    LOGOUT: "/auth/logout",
    USER_INFO: "/auth",
    FORGOT_PASSWORD: "/auth/forgot-password",
    VERIFY_TOKEN: "/auth/verify-token",
    RESEND_TOKEN: "/auth/resend-token",
  },
  ROLES: {
    GET_ALL: "/roles/get-all",
  },
  USERS: {
    CHANGE_PASSWORD: "/users/change-password",
    GET_ALL: "api/Users/",
    CREATE_USER: "/api/Users",
    GET_USERS_FILTER: "/api/Users/filter",
    UPDATE_USER: (id: string | number) => `/api/Users/${id}`,
    DELETE_USER: (id: string | number) => `/api/Users/${id}`,
    GET_USER_BY_ID: (id: string | number) => `/api/Users/${id}`,
    CHANGE_STATUS: "/users/change-status",
    SEARCH_USER: "/users/search",
    CHANGE_ROLE: "/users/change-role",
  },
  BLOGS: {
    GET_ALL: "/api/Blogs",
    CREATE: "/api/Blogs",
    GET_PAGED: "/api/Blogs/paged",
    GET_ACTIVE: "/api/Blogs/active",
    GET_ACTIVE_PAGED: "/api/Blogs/active/paged",
    SEARCH: "/api/Blogs/search",
    GET_BY_ID: (id: string | number) => `/api/Blogs/${id}`,
    UPDATE: (id: string | number) => `/api/Blogs/${id}`,
    DELETE: (id: string | number) => `/api/Blogs/${id}`,
    GET_BY_AUTHOR: (authorId: string | number) => `/api/Blogs/author/${authorId}`,
    GET_BY_AUTHOR_PAGED: (authorId: string | number) => `/api/Blogs/author/${authorId}/paged`,
    GET_BY_KEYWORD: (keywordId: string | number) => `/api/Blogs/keyword/${keywordId}`,
    GET_BY_KEYWORD_PAGED: (keywordId: string | number) => `/api/Blogs/keyword/${keywordId}/paged`,
    ADD_KEYWORD: (blogId: string | number, keywordId: string | number) => `/api/Blogs/${blogId}/keywords/${keywordId}`,
    REMOVE_KEYWORD: (blogId: string | number, keywordId: string | number) => `/api/Blogs/${blogId}/keywords/${keywordId}`,
    ADD_KEYWORDS: (blogId: string | number) => `/api/Blogs/${blogId}/keywords`,
    UPDATE_KEYWORDS: (blogId: string | number) => `/api/Blogs/${blogId}/keywords`,
  },
  KEYWORDS: {
    GET_ALL: "/api/Keywords",
    CREATE: "/api/Keywords",
    GET_BY_ID: (id: string | number) => `/api/Keywords/${id}`,
    UPDATE: (id: string | number) => `/api/Keywords/${id}`,
    DELETE: (id: string | number) => `/api/Keywords/${id}`,
    GET_BLOGS: (id: string | number) => `/api/Keywords/${id}/blogs`,
    SEARCH: "/api/Keywords/search",
    GET_BLOG_KEYWORDS: (blogId: string | number) => `/api/Keywords/blog/${blogId}`,
    GET_OR_CREATE: "/api/Keywords/get-or-create",
    EXISTS_BY_ID: (id: string | number) => `/api/Keywords/${id}/exists`,
    EXISTS: "/api/Keywords/exists",
  }
};
