export const API_CONSTANTS = {
  AUTH: {
    LOGIN: "api/auth/login",
    LOGOUT: "api/auth/logout",
    REFRESH_TOKEN: "api/auth/refresh-token",
    USER_INFO: "api/auth",
    FORGOT_PASSWORD: "api/auth/forgot-password",
    VERIFY_TOKEN: "api/auth/verify-token",
    RESEND_TOKEN: "api/auth/resend-token",
    SIGNUP: "api/auth/register",
    SIGNUP_PHOTOGRAPHER: "api/auth/register-photographer",
    VERIFY_OTP: "api/auth/verify-email-code",
    RESEND: "api/auth/resend-verification-code"
  },
  CLOUDINARY: {
    UPLOAD: "/api/Cloudinary/upload",
    UPLOAD_MULTIPLE: "/api/Cloudinary/upload-multiple",
    DELETE: "api/Cloudinary/delete",
    DELETE_MULTIPLE: "api/Cloudinary/delete-multiple",
    DELETE_ALL: (uploadType: string) => `api/Cloudinary/delete-all/${uploadType}`,
    TRANSFORM_URL: "/api/Cloudinary/transform-url"
  },
  PHOTO_PORTFOLIO: {
    GET_BY_USER_ID: (userId: string | number) => `/api/PhotoPortfolio/user/${userId}`,
    GET_MY_PORTFOLIOS: "/api/PhotoPortfolio/my-portfolios",
    GET_BY_ID: (id: string | number) => `/api/PhotoPortfolio/${id}`,
    UPDATE: (id: string | number) => `/api/PhotoPortfolio/${id}`,
    DELETE: (id: string | number) => `/api/PhotoPortfolio/${id}`,
    CREATE: "/api/PhotoPortfolio",
    CREATE_MULTIPLE: "/api/PhotoPortfolio/multiple",
    CREATE_MULTIPLE_FOR_USER: (userId: string | number) => `/api/PhotoPortfolio/user/${userId}/multiple`,
    DELETE_ALL: "/api/PhotoPortfolio/all",
    HAS_PORTFOLIO: "/api/PhotoPortfolio/has-portfolio",
    COUNT: "/api/PhotoPortfolio/count"
  },
  MEDIA: {
    SIGNATURE: "/api/Media/signature",
    CONFIRM: "/api/Media/confirm",
  },
  ROLES: {
    GET_ALL: "/roles/get-all",
  },
  USERS: {
    CHANGE_PASSWORD: "/users/change-password",
    GET_ALL: "api/Users/",
    CREATE_USER: "/api/Users",
    GET_USERS_FILTER: "/api/Users/filter",
    UPDATE_USER: (id: string | number) => `/api/Users/${id}`,
    DELETE_USER: (id: string | number) => `/api/Users/${id}`,
    GET_USER_BY_ID: (id: string | number) => `/api/Users/${id}`,
    CHANGE_STATUS: "/users/change-status",
    SEARCH_USER: "/users/search",
    CHANGE_ROLE: "/users/change-role",
    SEARCH_PHOTOGRAPHER_PENDING_LEVEL: "/api/Photographer/photographers/pending-level/search",
    SEARCH_PHOTOGRAPHERS: "/api/Photographer/photographers/search",
    UPDATE_PHOTOGRAPHER_LEVEL: (id: string | number) => `/api/Photographer/${id}/photographer-level`,
  },
  BLOGS: {
    GET_ALL: "/api/Blogs",
    CREATE: "/api/Blogs",
    GET_PAGED: "/api/Blogs/paged",
    GET_ACTIVE: "/api/Blogs/active",
    GET_ACTIVE_PAGED: "/api/Blogs/active/paged",
    SEARCH: "/api/Blogs/search",
    GET_BY_ID: (id: string | number) => `/api/Blogs/${id}`,
    UPDATE: (id: string | number) => `/api/Blogs/${id}`,
    DELETE: (id: string | number) => `/api/Blogs/${id}`,
    GET_BY_AUTHOR: (authorId: string | number) => `/api/Blogs/author/${authorId}`,
    GET_BY_AUTHOR_PAGED: (authorId: string | number) => `/api/Blogs/author/${authorId}/paged`,
    GET_BY_KEYWORD: (keywordId: string | number) => `/api/Blogs/keyword/${keywordId}`,
    GET_BY_KEYWORD_PAGED: (keywordId: string | number) => `/api/Blogs/keyword/${keywordId}/paged`,
    ADD_KEYWORD: (blogId: string | number, keywordId: string | number) => `/api/Blogs/${blogId}/keywords/${keywordId}`,
    REMOVE_KEYWORD: (blogId: string | number, keywordId: string | number) => `/api/Blogs/${blogId}/keywords/${keywordId}`,
    ADD_KEYWORDS: (blogId: string | number) => `/api/Blogs/${blogId}/keywords`,
    UPDATE_KEYWORDS: (blogId: string | number) => `/api/Blogs/${blogId}/keywords`,
  },
  KEYWORDS: {
    GET_ALL: "/api/Keywords",
    CREATE: "/api/Keywords",
    GET_BY_ID: (id: string | number) => `/api/Keywords/${id}`,
    UPDATE: (id: string | number) => `/api/Keywords/${id}`,
    DELETE: (id: string | number) => `/api/Keywords/${id}`,
    GET_BLOGS: (id: string | number) => `/api/Keywords/${id}/blogs`,
    SEARCH: "/api/Keywords/search",
    GET_BLOG_KEYWORDS: (blogId: string | number) => `/api/Keywords/blog/${blogId}`,
    GET_OR_CREATE: "/api/Keywords/get-or-create",
    EXISTS_BY_ID: (id: string | number) => `/api/Keywords/${id}/exists`,
    EXISTS: "/api/Keywords/exists",
  },
  STYLES: {
    GET_ALL: "/api/Styles",
    CREATE: "/api/Styles",
    UPDATE: (id: string | number) => `/api/Styles/${id}`,
    DELETE: (id: string | number) => `/api/Styles/${id}`,
  },
  PHOTO_TYPES: {
    GET_ALL: "/api/PhotoTypes",
    CREATE: "/api/PhotoTypes",
    GET_BY_ID: (id: string | number) => `/api/PhotoTypes/${id}`,
    UPDATE: (id: string | number) => `/api/PhotoTypes/${id}`,
    DELETE: (id: string | number) => `/api/PhotoTypes/${id}`,
    CHECK_NAME: "/api/PhotoTypes/check-name",
  },
  PHOTOGRAPHER_STYLES: {
    ADD_MULTIPLE: (userId: string | number) => `/api/PhotographerStyles/photographer/${userId}/styles/multiple`,
  },
  BOOKING: {
    GET_BY_ID: (id: string | number) => `/api/Booking/${id}`,
    UPDATE: (id: string | number) => `/api/Booking/${id}`,
    DELETE: (id: string | number) => `/api/Booking/${id}`,
    GET_BY_STATUS: (statusId: string | number) => `/api/Booking/status/${statusId}`,
    SEARCH: "/api/Booking/search",
    UPDATE_STATUS: (id: string | number) => `/api/Booking/${id}/status`,
    STATISTICS: "/api/Booking/statistics/detailed",
  },
  PAYMENTS: {
    SEARCH: "/api/Payments/search",
    SEARCH_SUMMARY: "/api/Payments/search/summary",
  }
};
